"""Narrow read ports for the platform support presentation boundary."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol
from uuid import UUID

from snaketracker.platform.events.envelope import DomainEvent
from snaketracker.platform.events.store import StreamKey

PAGE_SIZE = 30


class AdminReadPort(Protocol):
    def audit(
        self,
        *,
        actor: UUID | None,
        action: str,
        outcome: str,
        target_type: str | None = None,
        target_id: str | None = None,
    ) -> None: ...

    def overview(self) -> dict[str, Any]: ...
    def search(self, query: str) -> dict[str, list[dict[str, Any]]]: ...
    def accounts(
        self,
        query: str,
        status: str,
        household: str,
        role: str,
        registered_from: str,
        registered_before: str,
        page: int,
    ) -> list[dict[str, Any]]: ...
    def account(self, user_id: str) -> dict[str, Any] | None: ...
    def memberships(self, user_id: str) -> list[dict[str, Any]]: ...
    def sessions(self, user_id: str) -> list[dict[str, Any]]: ...
    def account_audit(self, user_id: str) -> list[dict[str, Any]]: ...
    def households(self, query: str, page: int) -> list[dict[str, Any]]: ...
    def household(self, household_id: str) -> dict[str, Any] | None: ...
    def household_bundle(self, household_id: str) -> dict[str, list[dict[str, Any]]]: ...
    def household_financial(self, household_id: str) -> dict[str, Any]: ...
    def subject(self, table: str, key: str, identifier: str) -> dict[str, Any] | None: ...
    def subject_events(
        self, household_id: str, subject_type: str, subject_id: str, *, limit: int = 100
    ) -> list[dict[str, Any]]: ...
    def events(self, query: str, field: str, page: int) -> list[dict[str, Any]]: ...
    def event(self, event_id: str) -> dict[str, Any] | None: ...
    def event_subjects(self, event_id: str) -> list[dict[str, Any]]: ...
    def event_relations(self, event: dict[str, Any]) -> list[dict[str, Any]]: ...
    def inventory_links(self, item_id: str) -> list[dict[str, Any]]: ...
    def animal_inventory_links(self, animal_id: str) -> list[dict[str, Any]]: ...
    def incident_identity(self, value: str) -> tuple[str, dict[str, Any]] | None: ...
    def subject_exists(
        self, household_id: str, subject_type: str, subject_id: str
    ) -> bool | None: ...
    def system(self) -> dict[str, Any]: ...
    def storage_health(self, attachment_root: Path, reference_root: Path) -> dict[str, Any]: ...
    def audit_rows(
        self,
        operator: str,
        action: str,
        target_type: str,
        target_id: str,
        since: str,
        until: str,
        page: int,
    ) -> list[dict[str, Any]]: ...


class AdminEventReadPort(Protocol):
    def load_stream(self, key: StreamKey) -> tuple[DomainEvent, ...]: ...
