#!/usr/bin/env python3
"""AT-PRODCOMP-01 semantic manifests for marked, disposable /tmp restores.

Run this same script with each release's Python environment. Snapshot reads are
SQLite mode=ro and query_only; no Settings, runtime secrets, HTTP or providers.
The comparison qualifies captured reads, not external backup/deployment gates.
"""

from __future__ import annotations

import argparse
import hashlib
import inspect
import json
import os
import re
import sqlite3
import sys
from dataclasses import fields, is_dataclass
from datetime import UTC, date, datetime
from enum import Enum
from functools import partial
from pathlib import Path
from typing import Any
from uuid import UUID

MARKER = "AT-PRODCOMP-01"
GUIDE_TABLES = {
    "care_guide_current",
    "care_guide_versions",
    "care_guide_sources",
    "care_guide_claims",
}
# Only calculation/checkpoint timestamps regenerated by isolated replay are ignored.
# Event recorded/occurred timestamps and household lifecycle timestamps remain exact.
DERIVED_TIMESTAMPS = {
    "reminder_facts": {"calculated_at"},
    "projection_definitions": {"updated_at"},
    "projection_checkpoints": {"updated_at"},
    "projection_generations": {"created_at", "activated_at"},
}
SQL_TOKENS = re.compile(
    r"--[^\n]*(?:\n|$)|/\*.*?\*/|'(?:''|[^'])*'|\"(?:\"\"|[^\"])*\"|"
    r"`(?:``|[^`])*`|\[[^\]]*\]|[A-Za-z_][A-Za-z_0-9]*",
    re.DOTALL,
)


def require_isolated_path(root: Path, target: Path) -> Path:
    """Validate before opening anything; reject symlinks and hardlinks as well."""
    root = root.absolute()
    if root.is_symlink() or root.resolve() != root:
        raise ValueError("Isolation root cannot contain symlinks")
    if root.parent != Path("/tmp") or not root.name.startswith("m66b-compat."):
        raise ValueError("Isolation root must be a direct /tmp/m66b-compat.* directory")
    marker = root / ".m66b-isolated"
    if marker.is_symlink() or not marker.is_file() or marker.read_text().strip() != MARKER:
        raise ValueError("Isolation root requires .m66b-isolated marker AT-PRODCOMP-01")
    absolute = target.absolute()
    if absolute != root and root not in absolute.parents:
        raise ValueError("Path is outside the marked isolation root")
    for component in (absolute, *absolute.parents):
        if component == root:
            break
        if component.is_symlink():
            raise ValueError("Isolated paths cannot contain symlinks")
    resolved = absolute.resolve()
    if resolved != root and root not in resolved.parents:
        raise ValueError("Path escapes isolation")
    if "runtime" in resolved.parts:
        raise ValueError("Runtime paths cannot be used for isolation")
    if resolved.is_file() and resolved.stat().st_nlink != 1:
        raise ValueError("Isolated files cannot be hardlinked")
    return resolved


def readonly(database: Path) -> sqlite3.Connection:
    connection = sqlite3.connect(database.as_uri() + "?mode=ro", uri=True)
    connection.execute("PRAGMA query_only=ON")
    connection.row_factory = sqlite3.Row
    return connection


def canonical(value: Any) -> Any:
    if is_dataclass(value) and not isinstance(value, type):
        return {item.name: canonical(getattr(value, item.name)) for item in fields(value)}
    if isinstance(value, dict):
        return {str(key): canonical(item) for key, item in value.items()}
    if isinstance(value, tuple | list):
        return [canonical(item) for item in value]
    if isinstance(value, set | frozenset):
        return sorted((canonical(item) for item in value), key=encoded)
    if isinstance(value, datetime):
        return value.astimezone(UTC).isoformat(timespec="microseconds")
    if isinstance(value, UUID | date):
        return str(value)
    if isinstance(value, Enum):
        return value.value
    if isinstance(value, bytes):
        return {"bytes_sha256": hashlib.sha256(value).hexdigest(), "size": len(value)}
    return value


def encoded(value: Any) -> str:
    return json.dumps(canonical(value), sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def digest(value: Any) -> str:
    return hashlib.sha256(encoded(value).encode()).hexdigest()


def summary(rows: list[dict[str, Any]], columns: list[str] | None = None) -> dict[str, Any]:
    ordered = sorted(rows, key=encoded)
    return {"row_count": len(rows), "sha256": digest(ordered), "columns": columns}


def quoted(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


def rows_for(connection: sqlite3.Connection, table: str) -> list[dict[str, Any]]:
    return [dict(row) for row in connection.execute(f"SELECT * FROM {quoted(table)}")]


def validate_projection_release(connection: sqlite3.Connection, *, registry=None):
    """Require the stored active catalog to match THIS release's actual registry.

    The release fingerprint is recorded separately from household content. It
    includes supported contracts and actual local strategy source hashes; a
    different release may correctly declare a different handler/fingerprint.
    """
    if registry is None:
        from snaketracker.infrastructure.product_experience.projections import (
            product_projection_registry,
        )

        registry = product_projection_registry
    definitions = [
        definition for group in registry.group_names for definition in registry.rebuild_group(group)
    ]
    stored = {row["projection_name"]: row for row in rows_for(connection, "projection_definitions")}
    if set(stored) != {definition.name for definition in definitions}:
        raise ValueError("Projection registry metadata has missing or unknown catalog definitions")
    generation_rows = rows_for(connection, "projection_generations")
    declarations = []
    for definition in sorted(definitions, key=lambda item: item.name):
        expected = {
            "projection_name": definition.name,
            "projection_schema_version": definition.schema_version,
            "handler_version": definition.handler_version,
            "consistency_class": definition.consistency_class,
            "rebuild_group": definition.rebuild_group,
            "physical_identifier": definition.physical_identifier,
            "source_kind": definition.source_kind,
            "freshness_threshold_seconds": definition.freshness_threshold_seconds,
        }
        actual = stored[definition.name]
        for key, value in expected.items():
            if actual.get(key) != value:
                raise ValueError(f"Projection registry metadata mismatch: {definition.name}.{key}")
        active = [
            row
            for row in generation_rows
            if row["projection_name"] == definition.name
            and row["generation_id"] == actual["active_generation_id"]
        ]
        if len(active) != 1 or active[0]["status"] != "active":
            raise ValueError("Projection registry metadata has no unique active generation")
        expected_physical = (
            f"{definition.physical_identifier}_{definition.components[0]}_g_"
            f"{UUID(actual['active_generation_id']).hex[:12]}"
        )
        if (
            active[0]["physical_identifier"] != expected_physical
            or active[0]["source_manifest_checksum"] != definition.source_manifest_checksum
        ):
            raise ValueError("Projection registry metadata has wrong active source fingerprint")
        source = inspect.getsourcefile(type(definition.strategy))
        if source is None:
            raise ValueError("Projection registry strategy has no inspectable local implementation")
        declarations.append(
            {
                **expected,
                "components": list(definition.components),
                "supported_contracts": sorted(definition.supported_contracts),
                "source_manifest_checksum": definition.source_manifest_checksum,
                "strategy_type": (
                    f"{type(definition.strategy).__module__}."
                    f"{type(definition.strategy).__qualname__}"
                ),
                "implementation_sha256": hashlib.sha256(Path(source).read_bytes()).hexdigest(),
            }
        )
    return {"validated": True, "registry_sha256": digest(declarations), "definitions": declarations}


def projection_table_map(connection: sqlite3.Connection, tables: set[str]):
    """Map only active physical generations to stable logical component identities."""
    names, ignored, replacements = {}, {}, {}
    if "projection_definitions" not in tables:
        return names, ignored, replacements
    definitions = rows_for(connection, "projection_definitions")
    generations = rows_for(connection, "projection_generations")
    for definition in definitions:
        active = definition["active_generation_id"]
        if active is None:
            raise ValueError("Projection has no active generation")
        logical = definition["projection_name"]
        replacements[active] = f"active:{logical}"
        for generation in generations:
            if generation["projection_name"] != logical:
                continue
            prefix = f"{definition['physical_identifier']}_"
            suffix = f"_g_{UUID(generation['generation_id']).hex[:12]}"
            for table in tables:
                if not table.startswith(prefix) or suffix not in table:
                    continue
                component, internal = table[len(prefix) :].split(suffix, 1)
                if generation["generation_id"] != active:
                    ignored[table] = "inactive retained/failed projection generation"
                elif internal and component == "fts":
                    ignored[table] = "FTS5 internal storage; active FTS content/query compared"
                else:
                    names[table] = f"projection:{logical}:{component}"
        # UUID-containing identifiers do not participate in household semantics.
        for table, name in names.items():
            if f"_g_{UUID(active).hex[:12]}" in table:
                replacements[table] = name
    return names, ignored, replacements


def schema_manifest(connection, names, ignored):
    """Compare schema behavior while normalizing only active physical identifiers.

    Table SQL retains CHECK/FK/UNIQUE/default definitions. Explicit indexes,
    triggers and views are compared even when their current rows are unchanged.
    SQL string literals are preserved, including strings resembling a generation
    identifier; they may be meaningful business behavior.
    """
    objects = list(
        connection.execute(
            "SELECT name,type,tbl_name,sql FROM sqlite_schema "
            "WHERE type IN ('table','view','index','trigger') "
            "AND name NOT LIKE 'sqlite_%' ORDER BY type,name"
        )
    )
    renames = dict(names)
    for name, _kind, owner, _sql in objects:
        if owner in names and name.startswith(owner + "_"):
            renames[name] = names[owner] + name[len(owner) :]

    def normalize_sql(sql):
        def identifier(match):
            token = match.group()
            if token.startswith(("'", "--", "/*")):
                return token
            if token.startswith('"'):
                raw = token[1:-1].replace('""', '"')
            elif token.startswith("`"):
                raw = token[1:-1].replace("``", "`")
            elif token.startswith("["):
                raw = token[1:-1]
            else:
                raw = token
            replacement = renames.get(raw)
            return '"' + replacement.replace('"', '""') + '"' if replacement else token

        return SQL_TOKENS.sub(identifier, sql)

    definitions, inventory = {}, []
    for name, kind, owner, sql in objects:
        logical = renames.get(name, name)
        item = {"name": name, "logical_name": logical, "type": kind, "owner": owner}
        reason = ignored.get(name) or ignored.get(owner)
        if reason:
            item["excluded_reason"] = reason
        else:
            if sql is None:
                raise ValueError("Explicit schema object has no SQL definition")
            definitions[f"{kind}:{logical}"] = {
                "type": kind,
                "owner": names.get(owner, owner),
                "sql_sha256": digest(normalize_sql(sql)),
            }
            item["schema_sha256"] = digest(sql)
        inventory.append(item)
    return definitions, inventory


def media_manifest(root, connection, tables, attachments, reference_images):
    files = []
    if "attachment_versions" in tables:
        extensions = {"image/jpeg": ".jpg", "image/png": ".png", "image/webp": ".webp"}
        for row in rows_for(connection, "attachment_versions"):
            extension = extensions.get(row["media_type"])
            if extension is None:
                raise ValueError("Unsupported attachment media type")
            path = attachments / "versions" / (UUID(row["storage_key"]).hex + extension)
            require_isolated_path(root, path)
            if not path.is_file():
                raise ValueError("Referenced attachment is missing")
            content = path.read_bytes()
            sha = hashlib.sha256(content).hexdigest()
            if sha != row["content_sha256"] or len(content) != row["size_bytes"]:
                raise ValueError("Referenced attachment content hash/size mismatch")
            files.append(
                {
                    "attachment_version_id": row["attachment_version_id"],
                    "sha256": sha,
                    "size": len(content),
                }
            )
    reference_files = []
    if "taxon_images" in tables:
        for row in rows_for(connection, "taxon_images"):
            filename = row.get("local_filename")
            if filename is None:
                continue
            if reference_images is None:
                raise ValueError("Referenced local reference image directory is required")
            path = require_isolated_path(root, reference_images / filename)
            if path.parent != reference_images or not path.is_file():
                raise ValueError("Referenced local reference image is missing or unsafe")
            content = path.read_bytes()
            if (
                hashlib.sha256(content).hexdigest() != row["local_sha256"]
                or len(content) != row["local_byte_size"]
            ):
                raise ValueError("Referenced local reference image hash/size mismatch")
    if reference_images is not None:
        for path in sorted(reference_images.rglob("*")):
            require_isolated_path(root, path)
            if path.is_file():
                reference_files.append(
                    {
                        "relative_path": str(path.relative_to(reference_images)),
                        "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
                    }
                )
    return {"attachments": summary(files), "reference_images": summary(reference_files)}


def capture_manifest(
    *, root, database, attachments, reference_images, cutoff, clock, release, semantic_reads=True
):
    database = require_isolated_path(root, database)
    attachments = require_isolated_path(root, attachments)
    if not database.is_file() or not attachments.is_dir():
        raise ValueError("Isolated database and restored attachment directory must exist")
    if reference_images is not None:
        reference_images = require_isolated_path(root, reference_images)
        if not reference_images.is_dir():
            raise ValueError("Restored reference image directory must exist")
    instant = datetime.fromisoformat(clock)
    if instant.tzinfo is None:
        raise ValueError("Controlled clock must include timezone")
    connection = readonly(database)
    try:
        connection.execute("BEGIN")
        integrity = [row[0] for row in connection.execute("PRAGMA integrity_check")]
        if integrity != ["ok"] or list(connection.execute("PRAGMA foreign_key_check")):
            raise ValueError("Isolated database integrity/foreign-key check failed")
        schema = list(
            connection.execute(
                "SELECT name,type,sql FROM sqlite_schema WHERE type IN ('table','view') "
                "AND name NOT LIKE 'sqlite_%' ORDER BY name"
            )
        )
        actual_tables = {row[0] for row in schema if row[1] == "table"}
        high_water = connection.execute(
            "SELECT coalesce(max(global_position),0) FROM domain_events"
        ).fetchone()[0]
        if cutoff < 0 or high_water != cutoff:
            raise ValueError(
                "Event high-water must equal common cutoff; refusing partial read models"
            )
        names, ignored, replacements = projection_table_map(connection, actual_tables)
        schema_objects, schema_object_inventory = schema_manifest(connection, names, ignored)
        projection_release = (
            validate_projection_release(connection)
            if "projection_definitions" in actual_tables
            else {"validated": False, "reason": "projection catalog absent"}
        )
        if "projection_checkpoints" in actual_tables:
            definitions = rows_for(connection, "projection_definitions")
            checkpoints = rows_for(connection, "projection_checkpoints")
            for definition in definitions:
                active = [
                    row
                    for row in checkpoints
                    if row["projection_name"] == definition["projection_name"]
                    and row["generation_id"] == definition["active_generation_id"]
                ]
                if len(active) != 1 or active[0]["last_global_position"] != cutoff:
                    raise ValueError("Active projection checkpoint has not reached common cutoff")
        boa_ids = (
            {
                row["taxon_id"]
                for row in rows_for(connection, "taxa")
                if row["accepted_scientific_name"] == "Boa constrictor"
            }
            if "taxa" in actual_tables
            else set()
        )
        manifests, reference, inventory = {}, {}, []
        for name, kind, sql in schema:
            logical = names.get(name, name)
            item = {"name": name, "logical_name": logical, "type": kind}
            if name in ignored:
                item["excluded_reason"] = ignored[name]
                inventory.append(item)
                continue
            rows = rows_for(connection, name)
            columns = [row[1] for row in connection.execute(f"PRAGMA table_info({quoted(name)})")]
            excluded = DERIVED_TIMESTAMPS.get(name, set())
            item["excluded_columns"] = sorted(excluded & set(columns))
            if name == "projection_generations":
                rows = [row for row in rows if row["status"] == "active"]
                excluded = excluded | {"validation_json", "source_manifest_checksum"}
                item["excluded_reason"] = (
                    "inactive lifecycle rows; validation evidence is release metadata"
                )
            if name == "projection_definitions":
                # Each field has just been checked against the actual binary's
                # registry. Keep release evolution in its own evidence section.
                excluded = excluded | {"handler_version", "projection_schema_version"}
            if name == "projection_checkpoints":
                rows = [row for row in rows if row["generation_id"] in replacements]
            if logical == "projection:global_search_fts:content":
                excluded = excluded | {"rowid"}
            item["excluded_columns"] = sorted(excluded & set(columns))
            clean = [
                {
                    key: replacements.get(value, value) if isinstance(value, str) else value
                    for key, value in row.items()
                    if key not in excluded
                }
                for row in rows
            ]
            if name in GUIDE_TABLES:
                reference[name] = summary([row for row in clean if row["taxon_id"] in boa_ids])
                clean = [row for row in clean if row["taxon_id"] not in boa_ids]
            manifests[logical] = summary(
                clean, [column for column in columns if column not in excluded]
            )
            item["row_count"] = len(rows)
            item["schema_sha256"] = digest(sql)
            inventory.append(item)
        result = {
            "manifest_version": 1,
            "context": {"cutoff": cutoff, "clock": canonical(instant)},
            "release": release,
            "database_sha256": hashlib.sha256(database.read_bytes()).hexdigest(),
            "schema_inventory": inventory,
            "schema_objects": schema_objects,
            "schema_object_inventory": schema_object_inventory,
            "tables": manifests,
            "boa_reference": reference,
            "media": media_manifest(root, connection, actual_tables, attachments, reference_images),
            "semantic_reads": {},
            "semantic_errors": {},
            "projection_release": projection_release,
            "external_required_evidence": [
                "encrypted backup verified and isolated restore",
                "actual old release environment identity",
                "isolated replay/rebuild evidence",
                "stored command retry without duplicate effects",
                "HTTP authorization boundaries for keeper and Admin/support routes",
                "candidate mixed-v1/v2 fixture and older-binary rejection",
            ],
        }
    finally:
        connection.close()
    if semantic_reads:
        result["semantic_reads"], result["semantic_errors"] = application_reads(database, instant)
        import snaketracker
        from snaketracker.infrastructure.product_experience.projections import (
            product_projection_registry,
        )
        from snaketracker.platform.events.registry import production_event_registry

        result["semantic_environment"] = {
            "python": sys.version,
            "package_path": str(Path(snaketracker.__file__).resolve()),
            "readable_contracts": sorted(production_event_registry.identities),
            "projection_groups": sorted(product_projection_registry.group_names),
        }
    return result


def application_reads(database: Path, instant: datetime):
    """Execute each release's real local read adapters; errors fail comparison closed."""
    from sqlalchemy import create_engine, text

    from snaketracker.application.animals import AnimalService
    from snaketracker.application.enclosures import EnclosureService
    from snaketracker.application.expenses import ExpenseService
    from snaketracker.application.identity import ROLE_CAPABILITIES
    from snaketracker.application.inventory import InventoryService
    from snaketracker.application.reminders import ReminderFactService
    from snaketracker.application.reports import ReportService
    from snaketracker.infrastructure.admin.read_repository import AdminReadRepository
    from snaketracker.infrastructure.animals.projections import SQLAlchemyAnimalCurrentProjection
    from snaketracker.infrastructure.enclosures.projections import (
        SQLAlchemyEnclosureCurrentProjection,
    )
    from snaketracker.infrastructure.events.sqlite_event_store import SQLAlchemyEventStore
    from snaketracker.infrastructure.expenses.projections import SQLAlchemyExpenseCurrentProjection
    from snaketracker.infrastructure.inventory.projections import (
        SQLAlchemyInventoryBalanceProjection,
    )
    from snaketracker.infrastructure.product_experience.projections import (
        product_projection_registry,
    )
    from snaketracker.infrastructure.product_experience.read_models import (
        SQLAlchemyProjectedEventReader,
    )
    from snaketracker.infrastructure.projections.sqlite_generations import (
        SQLiteProjectionGenerationManager,
    )
    from snaketracker.infrastructure.purchases.projections import SQLAlchemyInventoryCostProjection
    from snaketracker.infrastructure.reminders.projections import SQLAlchemyReminderProjection
    from snaketracker.infrastructure.search.fts import SQLAlchemyFTSSearchRepository
    from snaketracker.platform.events.store import StreamKey

    engine = create_engine("sqlite+pysqlite://", creator=lambda: readonly(database))
    store = SQLAlchemyEventStore(engine)
    animals = AnimalService(store, SQLAlchemyAnimalCurrentProjection(engine))
    enclosures = EnclosureService(store, SQLAlchemyEnclosureCurrentProjection(engine))
    inventory = InventoryService(store, SQLAlchemyInventoryBalanceProjection(engine))
    reminders = ReminderFactService(store, SQLAlchemyReminderProjection(engine))
    manager = SQLiteProjectionGenerationManager(engine, product_projection_registry)
    costs = SQLAlchemyInventoryCostProjection(engine, manager)
    admin = AdminReadRepository(engine)
    projected = SQLAlchemyProjectedEventReader(
        engine, manager, product_projection_registry, "report_facts"
    )
    reports = ReportService(
        animals, ExpenseService(store, SQLAlchemyExpenseCurrentProjection(engine)), projected
    )
    search = SQLAlchemyFTSSearchRepository(engine, manager)
    reads, errors = {}, {}

    def capture(key, operation):
        try:
            value = canonical(operation())
            reads[key] = {
                "sha256": digest(value),
                "count": len(value) if isinstance(value, list | dict) else 1,
            }
        except Exception as error:
            # Do not include potentially private data in exception strings.
            errors[key] = type(error).__name__

    try:
        with engine.connect() as connection:
            households = [
                UUID(value)
                for value in connection.execute(
                    text("SELECT household_id FROM household_summaries ORDER BY household_id")
                ).scalars()
            ]
            streams = list(
                connection.execute(
                    text(
                        "SELECT DISTINCT household_id,stream_type,stream_id FROM domain_events "
                        "ORDER BY household_id,stream_type,stream_id"
                    )
                )
            )
            operations = list(
                connection.execute(
                    text(
                        "SELECT * FROM idempotency_operations WHERE status='completed' "
                        "ORDER BY household_id,actor_user_id,operation_scope,idempotency_key"
                    )
                ).mappings()
            )
        for household, stream_type, stream_id in streams:
            key = StreamKey(UUID(household), stream_type, UUID(stream_id))
            capture(
                f"registered_stream:{household}:{stream_type}:{stream_id}",
                lambda key=key: store.load_stream(key),
            )
        for operation in operations:
            capture(
                f"idempotency_response:{digest(dict(operation))}",
                lambda operation=operation: store.stored_idempotency_response(
                    UUID(operation["household_id"]),
                    UUID(operation["actor_user_id"]),
                    operation["operation_scope"],
                    operation["idempotency_key"],
                    operation["command_hash"],
                ),
            )
        for household in households:
            prefix = str(household)
            capture(f"{prefix}:animal_profiles", partial(animals.list_profiles, household))
            capture(
                f"{prefix}:reminder_agenda", partial(reminders.agenda_for, household, now=instant)
            )
            capture(f"{prefix}:enclosures", partial(enclosures.list_profiles, household))
            capture(f"{prefix}:admin_household", partial(admin.household_bundle, prefix))
            capture(f"{prefix}:admin_financial", partial(admin.household_financial, prefix))
            for report in ("collection", "care", "expenses"):
                capture(
                    f"{prefix}:report:{report}",
                    partial(getattr(reports, report), household, generated_at=instant),
                )
            profiles = animals.list_profiles(household)
            for profile in profiles:
                capture(
                    f"{prefix}:effective_animal:{profile.animal_id}",
                    partial(animals.effective_history, household, profile.animal_id),
                )
                capture(
                    f"{prefix}:search:{profile.animal_id}",
                    partial(
                        search.search,
                        household,
                        ROLE_CAPABILITIES["owner"],
                        profile.name,
                        limit=100,
                    ),
                )
            for enclosure in enclosures.list_profiles(household):
                capture(
                    f"{prefix}:plants:{enclosure.enclosure_id}",
                    partial(
                        enclosures.plants, household, enclosure.enclosure_id, include_removed=True
                    ),
                )
                capture(
                    f"{prefix}:occupants:{enclosure.enclosure_id}",
                    partial(enclosures.occupants, household, enclosure.enclosure_id),
                )
                capture(
                    f"{prefix}:effective_enclosure:{enclosure.enclosure_id}",
                    partial(enclosures.effective_history, household, enclosure.enclosure_id),
                )
            for status in ("active", "archived"):
                capture(
                    f"{prefix}:inventory:{status}",
                    partial(inventory.list_balances, household, status=status),
                )
                for balance in inventory.list_balances(household, status=status):
                    capture(
                        f"{prefix}:fifo:{balance.item_id}",
                        partial(costs.summary_for, household, balance.item_id),
                    )
    except Exception as error:
        errors["application_read_setup"] = type(error).__name__
    finally:
        engine.dispose()
    return reads, errors


def compare_manifests(before, after):
    differences, expected = [], []
    for key in ("cutoff", "clock"):
        if before["context"][key] != after["context"][key]:
            differences.append(f"context.{key}")
    for area in ("tables", "media", "semantic_reads", "schema_objects"):
        if area not in before or area not in after:
            differences.append(f"{area}.missing_manifest_dimension")
            continue
        for name in sorted(set(before[area]) | set(after[area])):
            if before[area].get(name) != after[area].get(name):
                differences.append(f"{area}.{name}")
    for name in sorted(set(before["boa_reference"]) | set(after["boa_reference"])):
        if before["boa_reference"].get(name) != after["boa_reference"].get(name):
            expected.append(f"boa_reference.{name}")
    releases = [before.get("projection_release", {}), after.get("projection_release", {})]
    release_valid = all(
        item.get("validated") is True
        and item.get("registry_sha256") == digest(item.get("definitions"))
        for item in releases
    )
    if release_valid and releases[0] != releases[1]:
        expected.append("projection_release.validated_registry_evolution")
    required_contracts = {
        tuple(identity)
        for identity in before.get("semantic_environment", {}).get("readable_contracts", [])
    }
    readable_contracts = {
        tuple(identity)
        for identity in after.get("semantic_environment", {}).get("readable_contracts", [])
    }
    if not required_contracts <= readable_contracts:
        differences.append("semantic_environment.missing_old_readable_contracts")
    missing = []
    if not before["semantic_reads"] or not after["semantic_reads"]:
        missing.append("application semantic reads")
    if before["semantic_errors"] or after["semantic_errors"]:
        missing.append("successful application reads for every captured dimension")
    if not release_valid:
        missing.append("actual release projection registry metadata validation")
    return {
        "status": "passed" if not differences and not missing else "blocked",
        "scope": "captured semantic manifest comparison; external release gates remain required",
        "unexpected_differences": differences,
        "expected_differences": expected,
        "missing_evidence": missing,
        "before_semantic_errors": before["semantic_errors"],
        "after_semantic_errors": after["semantic_errors"],
        "external_required_evidence": before["external_required_evidence"],
        "projection_release": {"before": releases[0], "after": releases[1]},
    }


def rebuild_isolated(*, root, database, cutoff, clock):
    """Replay registered streams and rebuild asynchronous groups in a disposable copy.

    Synchronous projection tables are verified by preserved data and real read
    adapters; this operation does not claim to reconstruct those tables.
    """
    from sqlalchemy import text

    from snaketracker.application.reminders import ReminderFactService
    from snaketracker.infrastructure.database.engine import create_sqlite_engine
    from snaketracker.infrastructure.events.sqlite_event_store import SQLAlchemyEventStore
    from snaketracker.infrastructure.product_experience.projections import (
        product_projection_registry,
    )
    from snaketracker.infrastructure.projections.sqlite_generations import (
        SQLiteProjectionGenerationManager,
    )
    from snaketracker.infrastructure.reminders.projections import SQLAlchemyReminderProjection
    from snaketracker.platform.events.store import StreamKey

    database = require_isolated_path(root, database)
    instant = datetime.fromisoformat(clock)
    if instant.tzinfo is None:
        raise ValueError("Controlled clock must include timezone")
    connection = readonly(database)
    try:
        before = {
            table: summary(rows_for(connection, table))
            for table in ("domain_events", "event_subjects", "idempotency_operations")
        }
        high_water = connection.execute(
            "SELECT coalesce(max(global_position),0) FROM domain_events"
        ).fetchone()[0]
        if high_water != cutoff:
            raise ValueError("Rebuild high-water differs from common cutoff")
        streams = list(
            connection.execute(
                "SELECT DISTINCT household_id,stream_type,stream_id FROM domain_events "
                "ORDER BY household_id,stream_type,stream_id"
            )
        )
    finally:
        connection.close()
    engine = create_sqlite_engine(database, require_local_storage=False)
    groups = {}
    registered_events = 0
    try:
        store = SQLAlchemyEventStore(engine)
        # Validate every immutable event before any manager can silently skip a
        # contract absent from a handler's declared supported_contracts.
        for household, stream_type, stream_id in streams:
            registered_events += len(
                store.load_stream(StreamKey(UUID(household), stream_type, UUID(stream_id)))
            )
        manager = SQLiteProjectionGenerationManager(engine, product_projection_registry)
        for group in product_projection_registry.group_names:
            rebuilt = manager.rebuild(group)
            if rebuilt.high_water_position != cutoff or rebuilt.final_position != cutoff:
                raise ValueError("Fixture writer changed cutoff during projection rebuild")
            groups[group] = canonical(rebuilt)
        projection = SQLAlchemyReminderProjection(engine)
        reminders = ReminderFactService(store, projection)
        for rule in projection.all_rules():
            reminders.recalculate_rule(rule.household_id, rule.rule_id, now=instant)
        with engine.connect() as check:
            final_position = check.execute(
                text("SELECT coalesce(max(global_position),0) FROM domain_events")
            ).scalar_one()
        if final_position != cutoff:
            raise ValueError("Fixture writer changed cutoff during reminder calculation")
    finally:
        engine.dispose()
    connection = readonly(database)
    try:
        after = {table: summary(rows_for(connection, table)) for table in before}
    finally:
        connection.close()
    if before != after:
        raise ValueError("Replay changed immutable events, subjects or idempotency responses")
    return {
        "cutoff": cutoff,
        "clock": canonical(instant),
        "registered_event_count": registered_events,
        "projection_groups": groups,
        "immutable_events_unchanged": True,
        "synchronous_projection_reconstruction": (
            "not performed; preserved tables/read adapters compared"
        ),
    }


def write_private_json(root, path, value):
    path = require_isolated_path(root, path)
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(descriptor, "w") as output:
        output.write(json.dumps(value, sort_keys=True, indent=2) + "\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--isolation-root", required=True, type=Path)
    actions = parser.add_subparsers(dest="action", required=True)
    snapshot = actions.add_parser("snapshot")
    snapshot.add_argument("--database", required=True, type=Path)
    snapshot.add_argument("--attachments", required=True, type=Path)
    snapshot.add_argument("--reference-images", type=Path)
    snapshot.add_argument("--cutoff", required=True, type=int)
    snapshot.add_argument("--clock", required=True)
    snapshot.add_argument("--release", required=True)
    snapshot.add_argument("--output", required=True, type=Path)
    compare = actions.add_parser("compare")
    compare.add_argument("--before", required=True, type=Path)
    compare.add_argument("--after", required=True, type=Path)
    compare.add_argument("--output", required=True, type=Path)
    rebuild = actions.add_parser("rebuild")
    rebuild.add_argument("--database", required=True, type=Path)
    rebuild.add_argument("--cutoff", required=True, type=int)
    rebuild.add_argument("--clock", required=True)
    rebuild.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    try:
        if args.action == "rebuild":
            value = rebuild_isolated(
                root=args.isolation_root,
                database=args.database,
                cutoff=args.cutoff,
                clock=args.clock,
            )
            write_private_json(args.isolation_root, args.output, value)
            print(json.dumps({"rebuild": str(args.output), "cutoff": args.cutoff}, sort_keys=True))
            return 0
        if args.action == "snapshot":
            value = capture_manifest(
                root=args.isolation_root,
                database=args.database,
                attachments=args.attachments,
                reference_images=args.reference_images,
                cutoff=args.cutoff,
                clock=args.clock,
                release=args.release,
            )
            write_private_json(args.isolation_root, args.output, value)
            print(
                json.dumps(
                    {"manifest": str(args.output), "semantic_errors": value["semantic_errors"]},
                    sort_keys=True,
                )
            )
            return 0 if not value["semantic_errors"] else 1
        before = json.loads(require_isolated_path(args.isolation_root, args.before).read_text())
        after = json.loads(require_isolated_path(args.isolation_root, args.after).read_text())
        result = compare_manifests(before, after)
        write_private_json(args.isolation_root, args.output, result)
        print(
            json.dumps(
                {key: value for key, value in result.items() if key != "projection_release"},
                sort_keys=True,
            )
        )
        return 0 if result["status"] == "passed" else 1
    except (ValueError, OSError, sqlite3.Error) as error:
        parser.exit(2, f"Qualification blocked: {type(error).__name__}: {error}\n")


if __name__ == "__main__":
    raise SystemExit(main())
